version: '3.7'
services: 
    web:
        build: .
        stdin_open: true
        container_name: vuewebchat
        tty: true
        env_file: 
            - .env
        ports: 
            - "8000:80"
        volumes:
            - "/app/node_modules"
            - ".:/app"
        restart: unless-stopped